// /lib/utils/download.ts
import { logger } from "@/lib/utils/logger";

const downloadLogger = logger.withContext("download");

interface Message {
  role: string;
  content: string;
  [key: string]: unknown;
}

/**
 * Hàm nội bộ: Xử lý việc tạo file Blob và kích hoạt tải xuống
 */
export function downloadConversationAsTxt(
  messages: Message[],
  title: string = "conversation"
): void {
  if (!messages || messages.length === 0) {
    throw new Error("Nội dung trống, không thể tải về.");
  }

  // 1. Định dạng nội dung file text
  const date = new Date().toLocaleString("vi-VN");
  let content = `CONVERSATION EXPORT\nTitle: ${title}\nDate: ${date}\n----------------------------------------\n\n`;

  messages.forEach((msg) => {
    const role = msg.role === "user" ? "USER" : "AI";
    const text = msg.content || "[No content]";
    content += `[${role}]:\n${text}\n\n----------------------------------------\n\n`;
  });

  content += `End of export.\nGenerated by Vikini AI.`;

  // 2. Tạo Blob & Trigger Download
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;

  // Tên file an toàn (Sanitize filename)
  const safeTitle =
    String(title)
      .replace(/[^a-z0-9\u00C0-\u024F\s-]/gi, "")
      .trim() || "chat";
  link.download = `${safeTitle}_${Date.now()}.txt`;

  document.body.appendChild(link);
  link.click();

  // Dọn dẹp
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * MAIN FUNCTION: Tải hội thoại dựa trên ID (Tự động gọi API)
 * Dùng hàm này cho các nút bấm ở Sidebar hoặc Danh sách chat.
 */
export async function downloadConversationById(
  conversationId: string,
  conversationTitle: string
): Promise<boolean> {
  try {
    // 1. Gọi API lấy tin nhắn
    const res = await fetch(`/api/conversations?id=${conversationId}`);

    if (!res.ok) {
      throw new Error(`Lỗi kết nối: ${res.status} ${res.statusText}`);
    }

    const data = (await res.json()) as { messages?: Message[] };

    if (!data || !data.messages || data.messages.length === 0) {
      throw new Error("Cuộc hội thoại này chưa có tin nhắn nào.");
    }

    // 2. Thực hiện tải về
    downloadConversationAsTxt(data.messages, conversationTitle);
    return true; // Báo thành công
  } catch (err) {
    downloadLogger.error("Download Error:", err);
    throw err; // Ném lỗi ra để Component hiển thị Alert nếu cần
  }
}
