// Deep Research types

export type ResearchStatus = "planning" | "ready_to_execute" | "executing" | "completed" | "failed";

/**
 * Canonical list of valid agent model IDs.
 * Single source of truth — referenced by API routes, client hook, and UI.
 */
export const VALID_AGENTS = [
  "deep-research-preview-04-2026",
  "deep-research-max-preview-04-2026",
] as const;

export type ResearchAgent = (typeof VALID_AGENTS)[number];

/** Type guard for ResearchAgent — use instead of local VALID_AGENTS arrays */
export function isValidAgent(value: unknown): value is ResearchAgent {
  return typeof value === "string" && (VALID_AGENTS as readonly string[]).includes(value);
}

/** Active step during execution */
export type ResearchStep = "searching" | "analyzing" | "writing";

/** A research plan generated by the AI */
export interface ResearchPlan {
  topic: string;
  steps: string[];
  estimated_time_minutes: number;
  search_queries: string[];
}

/** A source referenced in the research report */
export interface ResearchSource {
  url: string;
  title: string;
  snippet?: string;
}

export interface ResearchThinkingSource {
  url: string;
  title: string;
  favicon?: string;
}

export interface ResearchTask {
  id: string;
  userId: string;
  query: string;
  agentModel: ResearchAgent;
  planText: string | null;
  reportText: string | null;
  status: ResearchStatus;
  currentStep?: ResearchStep;
  plan?: ResearchPlan;
  sources?: ResearchSource[];

  // Real-time transient data (not stored in DB, only returned by poll)
  thinkingText?: string;
  searchedSources?: ResearchThinkingSource[];
  planInteractionId: string | null;
  execInteractionId: string | null;
  conversationId: string | null;
  projectId: string | null;
  gemId: string | null;
  errorMessage: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface CreateResearchRequest {
  query: string;
  agentModel?: ResearchAgent;
  conversationId?: string;
  projectId?: string;
  gemId?: string;
}

export interface ApproveResearchRequest {
  feedback?: string;
}

export interface ResearchStatusResponse {
  task: ResearchTask;
  progress?: {
    phase: string;
    detail?: string;
  };
}
