// Deep Research types

export type ResearchStatus = "planning" | "ready_to_execute" | "executing" | "completed" | "failed";

export type ResearchAgent =
  | "deep-research-preview-04-2026"
  | "deep-research-max-preview-04-2026"
  | "deep-research-fast-04-2026";

/** Active step during execution */
export type ResearchStep = "searching" | "analyzing" | "writing";

/** A research plan generated by the AI */
export interface ResearchPlan {
  topic: string;
  steps: string[];
  estimated_time_minutes: number;
  search_queries: string[];
}

/** A source referenced in the research report */
export interface ResearchSource {
  url: string;
  title: string;
  snippet?: string;
}

export interface ResearchTask {
  id: string;
  userId: string;
  query: string;
  agentModel: ResearchAgent;
  planText: string | null;
  reportText: string | null;
  status: ResearchStatus;
  currentStep?: ResearchStep;
  plan?: ResearchPlan;
  sources?: ResearchSource[];
  planInteractionId: string | null;
  execInteractionId: string | null;
  conversationId: string | null;
  projectId: string | null;
  gemId: string | null;
  errorMessage: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface CreateResearchRequest {
  query: string;
  agentModel?: ResearchAgent;
  conversationId?: string;
  projectId?: string;
  gemId?: string;
}

export interface ApproveResearchRequest {
  feedback?: string;
}

export interface ResearchStatusResponse {
  task: ResearchTask;
  progress?: {
    phase: string;
    detail?: string;
  };
}
