-- =====================================================================================
-- User Data Migration
-- =====================================================================================
-- Inserts initial user profiles (existing users from ENV whitelist)
-- Version: 002
-- Date: 2025-12-29
-- =====================================================================================
-- IMPORTANT: Run this AFTER 001_admin_system.sql
-- =====================================================================================

-- Insert 3 existing users with their ranks
-- Note: UUIDs will be auto-generated by auth.users, but we need to link them
-- For now, we'll create profiles without UUID (will be filled during first login)

-- Alternative approach: Insert with placeholder UUIDs that will be updated on first login
-- Or better: Let the auth callback auto-create profiles on first login

-- =====================================================================================
-- OPTION 1: Pre-create profiles with known Google IDs (if available)
-- =====================================================================================
-- If you have the Google User IDs from auth.users, uncomment and fill:
-- INSERT INTO profiles (id, email, rank) VALUES
--   ('GOOGLE_USER_ID_1', 'wyemhu12@gmail.com', 'admin'),
--   ('GOOGLE_USER_ID_2', 'kimtuyentd267@gmail.com', 'pro'),
--   ('GOOGLE_USER_ID_3', 'heartbeattui@gmail.com', 'pro')
-- ON CONFLICT (id) DO UPDATE SET rank = EXCLUDED.rank, email = EXCLUDED.email;

-- =====================================================================================
-- OPTION 2: Mark these emails as "pre-approved" (whitelist table - optional)
-- =====================================================================================
-- We'll skip this and let auth callback auto-create profiles

-- =====================================================================================
-- OPTION 3: Create email-to-rank mapping for auth callback
-- =====================================================================================
-- Create a temporary mapping table that auth callback will use

CREATE TABLE IF NOT EXISTS temp_user_ranks (
  email TEXT PRIMARY KEY,
  rank TEXT NOT NULL CHECK (rank IN ('basic', 'pro', 'admin'))
);

-- Insert email-to-rank mappings
INSERT INTO temp_user_ranks (email, rank) VALUES
  ('wyemhu12@gmail.com', 'admin'),
  ('kimtuyentd267@gmail.com', 'pro'),
  ('heartbeattui@gmail.com', 'pro')
ON CONFLICT (email) DO UPDATE SET rank = EXCLUDED.rank;

-- =====================================================================================
-- VERIFICATION
-- =====================================================================================
-- Check the mappings
SELECT * FROM temp_user_ranks ORDER BY rank DESC, email;

-- =====================================================================================
-- NOTES
-- =====================================================================================
-- This table will be used by the auth callback to assign correct ranks on first login
-- After all users have logged in at least once, you can drop this table:
-- DROP TABLE temp_user_ranks;
